spring:
  cloud:
    config:
      override-system-properties: false


name:
  value: alibou

server:
  port: 8888

eureka:
  instance:
    hostname: discovery-service.default.svc.cluster.local
  client:
    service-url:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka/


