eureka:
  instance:
    hostname: discovery-service.default.svc.cluster.local
  client:
    service-url:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka/
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8888
