server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - RewritePath=/api/v1/customers(?<remaining>/?.*), /api/v1/customers${remaining}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/api/v1/orders(?<remaining>/?.*), /api/v1/orders${remaining}
        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/api/v1/products(?<remaining>/?.*), /api/v1/products${remaining}

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - RewritePath=/api/v1/payments(?<remaining>/?.*), /api/v1/payments${remaining}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      # URL služby Zipkin v K8s (název služby v default namespace)
      base-url: http://zipkin:9411
      endpoint: http://zipkin:9411/api/v2/spans



