server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/payment
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/payment
    username: alibou
    password: alibou
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka-service.default.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.alibou.ecommerce.notification.PaymentNotificationRequest
application:
  config:
    product-url: http://product-service.default.svc.cluster.local:8222/api/v1/products

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      base-url: http://zipkin:9411
      endpoint: http://zipkin:9411/api/v2/spans
