apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: claivent/micro:notification-service-0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8040
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: native
