adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  type: pvc
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi

sidecar:
  datasources:
    enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: true
        editable: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  hosts:
    - grafana.local
  tls: []
