# syntax=docker/dockerfile:1.7

########## BUILDER ##########
FROM eclipse-temurin:17-jdk AS build
WORKDIR /workspace

# 1) Nejdřív věci, které se mění nejmíň – aby se dobře kešovaly
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .

# Cache Maven repozitáře mezi buildy (BuildKit cache mount)
RUN chmod +x ./mvnw
RUN --mount=type=cache,target=/root/.m2 ./mvnw -B -q -DskipTests dependency:go-offline

# 2) Až pak zdrojáky
COPY src src

# Build s cache m2 (rychlejší inkrementální buildy)
RUN --mount=type=cache,target=/root/.m2 ./mvnw -B -q -DskipTests clean package

########## RUNTIME ##########
FROM eclipse-temurin:17-jre AS runtime
WORKDIR /app

# vezmeme jediný vyrobený JAR a pojmenujeme ho prostě app.jar
# (pokud jich bude víc, zúž vzor na config-server-*.jar)
COPY --from=build /workspace/target/*.jar /app/app.jar

EXPOSE 8888
ENTRYPOINT ["java","-jar","/app/app.jar"]
