apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service

  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service

  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      containers:
        - name: gateway-service

          image: claivent/micro:gateway-service-0.1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8222
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: native
