apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: claivent/micro:payment-service-0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: native
