spring:
  config:
    #import: optional:configserver:http://localhost:8888
    optional:configserver:http://config-server:
      default:
        svc:
          cluster:
            local:8888:

  application:
    name: discovery-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG