spring:
  config:
    #import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://config-server.default.svc.cluster.local:8888
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: [ B3, W3C ]
  zipkin:
    tracing:
      endpoint: http://zipkin.default.svc.cluster.local:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%mdc{traceId:-},spanId=%mdc{spanId:-}]"






















#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus, env
#  endpoint:
#    health:
#      show-details: always
#  tracing:
#    sampling:
#      probability: 1.0
#    export:
#      zipkin:
#        endpoint: http://zipkin.default.svc.cluster.local:9411/api/v2/spans



