apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 5050:5050 /var/lib/pgadmin']
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: 'False'
        image: dpage/pgadmin4
        imagePullPolicy: always
        name: pgadmin
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pgadmin-storage
      volumes:
      - name: pgadmin-storage
        persistentVolumeClaim:
          claimName: pgadmin-pvc
