apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels: { app: zipkin }
  template:
    metadata:
      labels: { app: zipkin }
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:3.4
          ports:
            - containerPort: 9411
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /zipkin
            - name: ZIPKIN_UI_BASEPATH
              value: /zipkin
            - name: STORAGE_TYPE
              value: postgres
            - name: POSTGRES_HOST
              value: postgres.default.svc.cluster.local
            - name: POSTGRES_DB
              value: zipkin
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: zipkin-postgres, key: username }
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef: { name: zipkin-postgres, key: password }


