apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: { app: zipkin }
  template:
    metadata:
      labels: { app: zipkin }
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:3.4
          ports:
            - containerPort: 9411
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /zipkin
            - name: ZIPKIN_UI_BASEPATH
              value: /zipkin
---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: NodePort
  ports:
    - port: 9411
      protocol: TCP
      targetPort: 9411
      nodePort: 30095
  selector:
    app: zipkin
