apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: dev
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      process.roles: broker,controller
      node.id: 0
      controller.quorum.voters: "0@my-kafka-cluster-kafka-0.my-kafka-cluster-kafka-brokers.dev.svc:9093"
      inter.broker.protocol.version: "3.6"
      log.message.format.version: "3.6"
    storage:
      type: ephemeral
  kafkaExporter:
    topicRegex: ".*"
  zookeeper: null
  entityOperator:
    topicOperator: {}
    userOperator: {}

